@startuml report sensor error sequence diagram

sensor <--  transsiapp_db: healthchek call
transsiapp_db <-- transsiapp_core: check for error reports
transsiapp_core --> transsiapp_frontend: send sensor error notification




@enduml